// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseUDBXFile() {
  return window['go']['main']['App']['CloseUDBXFile']();
}

export function GetCurrentFile() {
  return window['go']['main']['App']['GetCurrentFile']();
}

export function GetDatasetFields(arg1) {
  return window['go']['main']['App']['GetDatasetFields'](arg1);
}

export function ListDatasets() {
  return window['go']['main']['App']['ListDatasets']();
}

export function LoadDatasetPage(arg1, arg2) {
  return window['go']['main']['App']['LoadDatasetPage'](arg1, arg2);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenUDBXFile(arg1) {
  return window['go']['main']['App']['OpenUDBXFile'](arg1);
}
