// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CloseUDBXFile():Promise<void>;

export function GetCurrentFile():Promise<string>;

export function GetDatasetFields(arg1:string):Promise<Array<string>>;

export function ListDatasets():Promise<Array<main.DatasetInfoDTO>>;

export function LoadDatasetPage(arg1:string,arg2:number):Promise<main.PageData>;

export function OpenFileDialog():Promise<string>;

export function OpenUDBXFile(arg1:string):Promise<main.FileInfo>;
